# Site settings
author: Stefani King
title: Old School Advertisement for the WIN
header-img: img/home-bg.png
email: themrsking@gmail.com
copyright_name: Stefani King
description: > # this means to ignore newlines until "baseurl:"
  Look Up
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  themrsking

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
